pub const DLC_FEATURES_EU5: &[&str] = &[];

/// A list of music provided by DLCs, for people who don't have them
pub const DLC_MUSIC: &[&str] = &[];

pub const COMMON_DIRS: &[&str] = &[
    // Note that parent directories should not be listed except for the COMMON_SUBDIRS_OK ones,
    // where only the parent directory should be listed.
    "common/achievements",
    "common/advances",
    "common/age",
    "common/ai_diplochance",
    "common/alert_descriptions",
    "common/artist_types",
    "common/artist_work",
    "common/attribute_columns",
    "common/auto_modifiers",
    "common/avatars",
    "common/biases",
    "common/building_categories",
    "common/building_types",
    "common/cabinet_actions",
    "common/casus_belli",
    "common/character_interactions",
    "common/child_educations",
    "common/climates",
    "common/coat_of_arms/coat_of_arms",
    "common/coat_of_arms/options",
    "common/coat_of_arms/template_lists",
    "common/country_description_categories",
    "common/country_interactions",
    "common/country_ranks",
    "common/culture_groups",
    "common/cultures",
    "common/customizable_localization",
    "common/death_reason",
    "common/designated_heir_reason",
    "common/diplomatic_costs",
    "common/disasters",
    "common/diseases",
    "common/effect_localization",
    "common/employment_systems",
    "common/estate_privileges",
    "common/estates",
    "common/ethnicities",
    "common/flag_definitions",
    "common/formable_countries",
    "common/game_concepts",
    "common/game_rules",
    "common/generic_action_ai_lists",
    "common/generic_actions",
    "common/genes",
    "common/gods",
    "common/goods",
    "common/goods_demand",
    "common/goods_demand_category",
    "common/government_reforms",
    "common/government_types",
    "common/hegemons",
    "common/heir_selections",
    "common/historical_scores",
    "common/holy_site_types",
    "common/holy_sites",
    "common/institution",
    "common/insults",
    "common/international_organization_land_ownership_rules",
    "common/international_organization_payments",
    "common/international_organization_special_statuses",
    "common/international_organizations",
    "common/join_war_rules",
    "common/language_families",
    "common/languages",
    "common/laws",
    "common/levies",
    "common/location_ranks",
    "common/missions",
    "common/music_player_tracks",
    "common/modifier_icons",
    "common/modifier_type_definitions",
    "common/named_colors",
    "common/on_action",
    "common/parliament_agendas",
    "common/parliament_issues",
    "common/parliament_types",
    "common/peace_treaties",
    "common/persistent_dna",
    "common/pop_types",
    "common/prices",
    "common/production_methods",
    "common/recruitment_method",
    "common/regencies",
    "common/religion_groups",
    "common/religions",
    "common/religious_aspects",
    "common/religious_factions",
    "common/religious_figures",
    "common/religious_focuses",
    "common/religious_schools",
    "common/resolutions",
    "common/rival_criteria",
    "common/road_types",
    "common/scenarios",
    "common/script_values",
    "common/scriptable_hints",
    "common/scripted_country_names",
    "common/scripted_diplomatic_objectives",
    "common/scripted_effects",
    "common/scripted_geography",
    "common/scripted_lists",
    "common/scripted_relations",
    "common/scripted_triggers",
    "common/situations",
    "common/societal_values",
    "common/static_modifiers",
    "common/subject_military_stances",
    "common/subject_types",
    "common/tests",
    "common/topography",
    "common/town_setups",
    "common/trait_flavor",
    "common/traits",
    "common/trigger_localization",
    "common/tutorial_lesson_chains",
    "common/tutorial_lessons",
    "common/unit_abilities",
    "common/unit_categories",
    "common/unit_formation_preference",
    "common/unit_types",
    "common/vegetation",
    "common/wargoals",
];

// TODO: EU5 verify
pub const COMMON_SUBDIRS_OK: &[&str] = &["common/defines"];

pub const FOCUS_TYPES: &[&str] = &["adm", "mil", "dip"];

pub const CURRENCIES: &[&str] = &[
    "prestige",
    "gold",
    "doom",
    "harmony",
    "manpower",
    "sailors",
    "honor",
    "karma",
    "purity",
    "yanantin",
    "honor",
    "horde_unity",
    "righteousness",
    "rite_power",
    "self_control",
    "tribal_cohesion",
    "stability",
    "government_power",
    "religious_influence",
    "legitimacy",
    "war_exhaustion",
    "army_tradition",
    "inflation",
];

pub const COUNTRY_TYPES: &[&str] = &[
    "location",
    "pop",
    "building",
    "army",
    "navy",
];

pub const CHARACTER_TRAIT_CATEGORY: &[&str] =
    &["admiral", "artist", "explorer", "general", "child", "ruler", "none"];
